### ISSUE TITLE
Map work on iOS, but don't work markers and events

### ISSUE THREAD

**Issue by alexsbobylev** [planxyz/react-native-maps-google#2]
Hi! Thanks for the work you've done!

The map is displayed, but does not run the event, no markers are placed. What could be the problem? Here is my code:

`<GoogleMap
          didTapMarker: {function(event) {
              alertIOS.alert('Info', 'Card');
          }}
          cameraPosition={{auto: true, zoom: 16}}
          scrollGestures={true}
          zoomGestures={true}
          tiltGestures={true}
          rotateGestures={true}
          consumesGesturesInView={true}
          compassButton={true}
          myLocationButton={true}
          indoorPicker={true}
          allowScrollGesturesDuringRotateOrZoom={true}
          style={styles.map}
          markers={[
            {
                id: 'marker-100',
                latitude: 55.823228,
                longitude: 49.145645
            }
          ]}
      />`

Error after add any event:
![2016-07-11 15 33 00](https://cloud.githubusercontent.com/assets/4498226/16730645/2c14a326-4785-11e6-83f6-209725d872d4.png)

**Comment by melvyn-planxyz** [comment]
Hi Alex, thanks for your interest :)

What's on your line 24 from `index.ios.js`?

**Comment by alexsbobylev** [comment]
Thanks for answer, Melvyn!

![2016-07-12 10 40 24](https://cloud.githubusercontent.com/assets/4498226/16758931/895998fc-4825-11e6-882c-60371cc0e78b.png)

**Comment by melvyn-planxyz** [comment]
If you have the import statement:
`import GoogleMap from 'react-native-maps-google';` in the beginning of your `index.ios.js`, this will be a simple syntax problem as the error says "Syntax" error. 

I suggest you to:
1. Use javascript formatter tool to reformat and reindent your javascript code
2. Use linter (ESLint is a good one)
3. Try to find where the syntax problem occurred.

**Comment by alexsbobylev** [comment]
This is not a syntax error. If you remove the error event no map is displayed. Once set up an event, an error occurs.

Screenshot beginning of the file

![2016-07-12 11 18 06](https://cloud.githubusercontent.com/assets/4498226/16760067/26527e30-482b-11e6-90ec-65a8a795743d.png)

**Comment by alexsbobylev** [comment]
**Full code (index.ios.js)**

```
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  AlertIOS,

  TouchableHighlight
} from 'react-native';

import GoogleMap from 'react-native-maps-google';

class Project extends Component {
  render() {
    return (
      <View style={styles.container}>
       <GoogleMap
          cameraPosition={{auto: true, zoom: 16}}
          scrollGestures={true}
          zoomGestures={true}
          tiltGestures={true}
          rotateGestures={true}
          consumesGesturesInView={true}
          compassButton={true}
          myLocationButton={true}
          indoorPicker={true}
          allowScrollGesturesDuringRotateOrZoom={true}
          style={styles.map}
          markers={[
            {
                id: 'marker-100',
                latitude: 55.823228,
                longitude: 49.145645,
            }
          ]},
         didTapMarker: {function(event) {
          console.log(event.name);
        }}
      />
      <TouchableHighlight style={styles.button} onPress={() => AlertIOS.alert('Info', 'Test')}>
        <Text style={styles.buttonText}>
          Ok
        </Text>
      </TouchableHighlight>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
  map: {
    width: 300,
    height: 500
  },
  button: {
    width: 300,
    height: 40,
    marginTop: 20,
    alignItems: 'center',
    backgroundColor: '#48BBEC',
  },
  buttonText: {
    color: 'white',
    alignItems: 'center',
    marginTop: 10
}

});

AppRegistry.registerComponent('Project', () => Project);

```
